# �Զ�������
kafka:
  topic: cities

# ����Kafka
spring:
  kafka:
    bootstrap-servers: kafkaos1:9092,kafkaos2:9092,kafkaos3:9092
      # producer:   # ����������
      # key-serializer: org.apache.kafka.common.serialization.StringSerializer
    # value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:   # ����������
      group-id: group0  # ��������
      # key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


